/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

/// <reference types="unplugin-vue-router/client" />

import type {
  // type safe route locations
  RouteLocationTypedList,
  RouteLocationResolvedTypedList,
  RouteLocationNormalizedTypedList,
  RouteLocationNormalizedLoadedTypedList,
  RouteLocationAsString,
  RouteLocationAsRelativeTypedList,
  RouteLocationAsPathTypedList,

  // helper types
  // route definitions
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,

  // vue-router extensions
  _RouterTyped,
  RouterLinkTyped,
  RouterLinkPropsTyped,
  NavigationGuard,
  UseLinkFnTyped,

  // data fetching
  _DataLoader,
  _DefineLoaderOptions,
} from 'unplugin-vue-router/types'

declare module 'vue-router/auto/routes' {
  export interface RouteNamedMap {
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'access-control': RouteRecordInfo<'access-control', '/access-control', Record<never, never>, Record<never, never>>,
    'apps-email-filter': RouteRecordInfo<'apps-email-filter', '/apps/email/:filter', { filter: ParamValue<true> }, { filter: ParamValue<false> }>,
    'apps-email-label': RouteRecordInfo<'apps-email-label', '/apps/email/:label', { label: ParamValue<true> }, { label: ParamValue<false> }>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'not-authorized': RouteRecordInfo<'not-authorized', '/not-authorized', Record<never, never>, Record<never, never>>,
    'register': RouteRecordInfo<'register', '/register', Record<never, never>, Record<never, never>>,
    'ui-apps-academy-course-details': RouteRecordInfo<'ui-apps-academy-course-details', '/ui/apps/academy/course-details', Record<never, never>, Record<never, never>>,
    'ui-apps-academy-dashboard': RouteRecordInfo<'ui-apps-academy-dashboard', '/ui/apps/academy/dashboard', Record<never, never>, Record<never, never>>,
    'ui-apps-academy-my-course': RouteRecordInfo<'ui-apps-academy-my-course', '/ui/apps/academy/my-course', Record<never, never>, Record<never, never>>,
    'ui-apps-calendar': RouteRecordInfo<'ui-apps-calendar', '/ui/apps/calendar', Record<never, never>, Record<never, never>>,
    'ui-apps-chat': RouteRecordInfo<'ui-apps-chat', '/ui/apps/chat', Record<never, never>, Record<never, never>>,
    'ui-apps-ecommerce-customer-details-id': RouteRecordInfo<'ui-apps-ecommerce-customer-details-id', '/ui/apps/ecommerce/customer/details/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'ui-apps-ecommerce-customer-list': RouteRecordInfo<'ui-apps-ecommerce-customer-list', '/ui/apps/ecommerce/customer/list', Record<never, never>, Record<never, never>>,
    'ui-apps-ecommerce-manage-review': RouteRecordInfo<'ui-apps-ecommerce-manage-review', '/ui/apps/ecommerce/manage-review', Record<never, never>, Record<never, never>>,
    'ui-apps-ecommerce-order-details-id': RouteRecordInfo<'ui-apps-ecommerce-order-details-id', '/ui/apps/ecommerce/order/details/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'ui-apps-ecommerce-order-list': RouteRecordInfo<'ui-apps-ecommerce-order-list', '/ui/apps/ecommerce/order/list', Record<never, never>, Record<never, never>>,
    'ui-apps-ecommerce-product-add': RouteRecordInfo<'ui-apps-ecommerce-product-add', '/ui/apps/ecommerce/product/add', Record<never, never>, Record<never, never>>,
    'ui-apps-ecommerce-product-category-list': RouteRecordInfo<'ui-apps-ecommerce-product-category-list', '/ui/apps/ecommerce/product/category-list', Record<never, never>, Record<never, never>>,
    'ui-apps-ecommerce-product-list': RouteRecordInfo<'ui-apps-ecommerce-product-list', '/ui/apps/ecommerce/product/list', Record<never, never>, Record<never, never>>,
    'ui-apps-ecommerce-referrals': RouteRecordInfo<'ui-apps-ecommerce-referrals', '/ui/apps/ecommerce/referrals', Record<never, never>, Record<never, never>>,
    'ui-apps-ecommerce-settings': RouteRecordInfo<'ui-apps-ecommerce-settings', '/ui/apps/ecommerce/settings', Record<never, never>, Record<never, never>>,
    'ui-apps-email': RouteRecordInfo<'ui-apps-email', '/ui/apps/email', Record<never, never>, Record<never, never>>,
    'ui-apps-invoice-add': RouteRecordInfo<'ui-apps-invoice-add', '/ui/apps/invoice/add', Record<never, never>, Record<never, never>>,
    'ui-apps-invoice-edit-id': RouteRecordInfo<'ui-apps-invoice-edit-id', '/ui/apps/invoice/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'ui-apps-invoice-list': RouteRecordInfo<'ui-apps-invoice-list', '/ui/apps/invoice/list', Record<never, never>, Record<never, never>>,
    'ui-apps-invoice-preview-id': RouteRecordInfo<'ui-apps-invoice-preview-id', '/ui/apps/invoice/preview/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'ui-apps-logistics-dashboard': RouteRecordInfo<'ui-apps-logistics-dashboard', '/ui/apps/logistics/dashboard', Record<never, never>, Record<never, never>>,
    'ui-apps-logistics-fleet': RouteRecordInfo<'ui-apps-logistics-fleet', '/ui/apps/logistics/fleet', Record<never, never>, Record<never, never>>,
    'ui-apps-permissions': RouteRecordInfo<'ui-apps-permissions', '/ui/apps/permissions', Record<never, never>, Record<never, never>>,
    'ui-apps-roles': RouteRecordInfo<'ui-apps-roles', '/ui/apps/roles', Record<never, never>, Record<never, never>>,
    'ui-apps-user-list': RouteRecordInfo<'ui-apps-user-list', '/ui/apps/user/list', Record<never, never>, Record<never, never>>,
    'ui-apps-user-view-id': RouteRecordInfo<'ui-apps-user-view-id', '/ui/apps/user/view/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'ui-charts-apex-chart': RouteRecordInfo<'ui-charts-apex-chart', '/ui/charts/apex-chart', Record<never, never>, Record<never, never>>,
    'ui-charts-chartjs': RouteRecordInfo<'ui-charts-chartjs', '/ui/charts/chartjs', Record<never, never>, Record<never, never>>,
    'ui-components-alert': RouteRecordInfo<'ui-components-alert', '/ui/components/alert', Record<never, never>, Record<never, never>>,
    'ui-components-avatar': RouteRecordInfo<'ui-components-avatar', '/ui/components/avatar', Record<never, never>, Record<never, never>>,
    'ui-components-badge': RouteRecordInfo<'ui-components-badge', '/ui/components/badge', Record<never, never>, Record<never, never>>,
    'ui-components-button': RouteRecordInfo<'ui-components-button', '/ui/components/button', Record<never, never>, Record<never, never>>,
    'ui-components-chip': RouteRecordInfo<'ui-components-chip', '/ui/components/chip', Record<never, never>, Record<never, never>>,
    'ui-components-dialog': RouteRecordInfo<'ui-components-dialog', '/ui/components/dialog', Record<never, never>, Record<never, never>>,
    'ui-components-expansion-panel': RouteRecordInfo<'ui-components-expansion-panel', '/ui/components/expansion-panel', Record<never, never>, Record<never, never>>,
    'ui-components-list': RouteRecordInfo<'ui-components-list', '/ui/components/list', Record<never, never>, Record<never, never>>,
    'ui-components-menu': RouteRecordInfo<'ui-components-menu', '/ui/components/menu', Record<never, never>, Record<never, never>>,
    'ui-components-pagination': RouteRecordInfo<'ui-components-pagination', '/ui/components/pagination', Record<never, never>, Record<never, never>>,
    'ui-components-progress-circular': RouteRecordInfo<'ui-components-progress-circular', '/ui/components/progress-circular', Record<never, never>, Record<never, never>>,
    'ui-components-progress-linear': RouteRecordInfo<'ui-components-progress-linear', '/ui/components/progress-linear', Record<never, never>, Record<never, never>>,
    'ui-components-snackbar': RouteRecordInfo<'ui-components-snackbar', '/ui/components/snackbar', Record<never, never>, Record<never, never>>,
    'ui-components-tabs': RouteRecordInfo<'ui-components-tabs', '/ui/components/tabs', Record<never, never>, Record<never, never>>,
    'ui-components-timeline': RouteRecordInfo<'ui-components-timeline', '/ui/components/timeline', Record<never, never>, Record<never, never>>,
    'ui-components-tooltip': RouteRecordInfo<'ui-components-tooltip', '/ui/components/tooltip', Record<never, never>, Record<never, never>>,
    'ui-dashboards-analytics': RouteRecordInfo<'ui-dashboards-analytics', '/ui/dashboards/analytics', Record<never, never>, Record<never, never>>,
    'ui-dashboards-crm': RouteRecordInfo<'ui-dashboards-crm', '/ui/dashboards/crm', Record<never, never>, Record<never, never>>,
    'ui-dashboards-ecommerce': RouteRecordInfo<'ui-dashboards-ecommerce', '/ui/dashboards/ecommerce', Record<never, never>, Record<never, never>>,
    'ui-extensions-swiper': RouteRecordInfo<'ui-extensions-swiper', '/ui/extensions/swiper', Record<never, never>, Record<never, never>>,
    'ui-extensions-tour': RouteRecordInfo<'ui-extensions-tour', '/ui/extensions/tour', Record<never, never>, Record<never, never>>,
    'ui-forgot-password': RouteRecordInfo<'ui-forgot-password', '/ui/forgot-password', Record<never, never>, Record<never, never>>,
    'ui-forms-autocomplete': RouteRecordInfo<'ui-forms-autocomplete', '/ui/forms/autocomplete', Record<never, never>, Record<never, never>>,
    'ui-forms-checkbox': RouteRecordInfo<'ui-forms-checkbox', '/ui/forms/checkbox', Record<never, never>, Record<never, never>>,
    'ui-forms-combobox': RouteRecordInfo<'ui-forms-combobox', '/ui/forms/combobox', Record<never, never>, Record<never, never>>,
    'ui-forms-custom-input': RouteRecordInfo<'ui-forms-custom-input', '/ui/forms/custom-input', Record<never, never>, Record<never, never>>,
    'ui-forms-date-time-picker': RouteRecordInfo<'ui-forms-date-time-picker', '/ui/forms/date-time-picker', Record<never, never>, Record<never, never>>,
    'ui-forms-editors': RouteRecordInfo<'ui-forms-editors', '/ui/forms/editors', Record<never, never>, Record<never, never>>,
    'ui-forms-file-input': RouteRecordInfo<'ui-forms-file-input', '/ui/forms/file-input', Record<never, never>, Record<never, never>>,
    'ui-forms-form-layouts': RouteRecordInfo<'ui-forms-form-layouts', '/ui/forms/form-layouts', Record<never, never>, Record<never, never>>,
    'ui-forms-form-validation': RouteRecordInfo<'ui-forms-form-validation', '/ui/forms/form-validation', Record<never, never>, Record<never, never>>,
    'ui-forms-form-wizard-icons': RouteRecordInfo<'ui-forms-form-wizard-icons', '/ui/forms/form-wizard-icons', Record<never, never>, Record<never, never>>,
    'ui-forms-form-wizard-numbered': RouteRecordInfo<'ui-forms-form-wizard-numbered', '/ui/forms/form-wizard-numbered', Record<never, never>, Record<never, never>>,
    'ui-forms-radio': RouteRecordInfo<'ui-forms-radio', '/ui/forms/radio', Record<never, never>, Record<never, never>>,
    'ui-forms-range-slider': RouteRecordInfo<'ui-forms-range-slider', '/ui/forms/range-slider', Record<never, never>, Record<never, never>>,
    'ui-forms-rating': RouteRecordInfo<'ui-forms-rating', '/ui/forms/rating', Record<never, never>, Record<never, never>>,
    'ui-forms-select': RouteRecordInfo<'ui-forms-select', '/ui/forms/select', Record<never, never>, Record<never, never>>,
    'ui-forms-slider': RouteRecordInfo<'ui-forms-slider', '/ui/forms/slider', Record<never, never>, Record<never, never>>,
    'ui-forms-switch': RouteRecordInfo<'ui-forms-switch', '/ui/forms/switch', Record<never, never>, Record<never, never>>,
    'ui-forms-textarea': RouteRecordInfo<'ui-forms-textarea', '/ui/forms/textarea', Record<never, never>, Record<never, never>>,
    'ui-forms-textfield': RouteRecordInfo<'ui-forms-textfield', '/ui/forms/textfield', Record<never, never>, Record<never, never>>,
    'ui-front-pages-checkout': RouteRecordInfo<'ui-front-pages-checkout', '/ui/front-pages/checkout', Record<never, never>, Record<never, never>>,
    'ui-front-pages-help-center': RouteRecordInfo<'ui-front-pages-help-center', '/ui/front-pages/help-center', Record<never, never>, Record<never, never>>,
    'ui-front-pages-help-center-article-title': RouteRecordInfo<'ui-front-pages-help-center-article-title', '/ui/front-pages/help-center/article/:title', { title: ParamValue<true> }, { title: ParamValue<false> }>,
    'ui-front-pages-landing-page': RouteRecordInfo<'ui-front-pages-landing-page', '/ui/front-pages/landing-page', Record<never, never>, Record<never, never>>,
    'ui-front-pages-payment': RouteRecordInfo<'ui-front-pages-payment', '/ui/front-pages/payment', Record<never, never>, Record<never, never>>,
    'ui-front-pages-pricing': RouteRecordInfo<'ui-front-pages-pricing', '/ui/front-pages/pricing', Record<never, never>, Record<never, never>>,
    'ui-pages-account-settings-tab': RouteRecordInfo<'ui-pages-account-settings-tab', '/ui/pages/account-settings/:tab', { tab: ParamValue<true> }, { tab: ParamValue<false> }>,
    'ui-pages-authentication-forgot-password-v1': RouteRecordInfo<'ui-pages-authentication-forgot-password-v1', '/ui/pages/authentication/forgot-password-v1', Record<never, never>, Record<never, never>>,
    'ui-pages-authentication-forgot-password-v2': RouteRecordInfo<'ui-pages-authentication-forgot-password-v2', '/ui/pages/authentication/forgot-password-v2', Record<never, never>, Record<never, never>>,
    'ui-pages-authentication-login-v1': RouteRecordInfo<'ui-pages-authentication-login-v1', '/ui/pages/authentication/login-v1', Record<never, never>, Record<never, never>>,
    'ui-pages-authentication-login-v2': RouteRecordInfo<'ui-pages-authentication-login-v2', '/ui/pages/authentication/login-v2', Record<never, never>, Record<never, never>>,
    'ui-pages-authentication-register-multi-steps': RouteRecordInfo<'ui-pages-authentication-register-multi-steps', '/ui/pages/authentication/register-multi-steps', Record<never, never>, Record<never, never>>,
    'ui-pages-authentication-register-v1': RouteRecordInfo<'ui-pages-authentication-register-v1', '/ui/pages/authentication/register-v1', Record<never, never>, Record<never, never>>,
    'ui-pages-authentication-register-v2': RouteRecordInfo<'ui-pages-authentication-register-v2', '/ui/pages/authentication/register-v2', Record<never, never>, Record<never, never>>,
    'ui-pages-authentication-reset-password-v1': RouteRecordInfo<'ui-pages-authentication-reset-password-v1', '/ui/pages/authentication/reset-password-v1', Record<never, never>, Record<never, never>>,
    'ui-pages-authentication-reset-password-v2': RouteRecordInfo<'ui-pages-authentication-reset-password-v2', '/ui/pages/authentication/reset-password-v2', Record<never, never>, Record<never, never>>,
    'ui-pages-authentication-two-steps-v1': RouteRecordInfo<'ui-pages-authentication-two-steps-v1', '/ui/pages/authentication/two-steps-v1', Record<never, never>, Record<never, never>>,
    'ui-pages-authentication-two-steps-v2': RouteRecordInfo<'ui-pages-authentication-two-steps-v2', '/ui/pages/authentication/two-steps-v2', Record<never, never>, Record<never, never>>,
    'ui-pages-authentication-verify-email-v1': RouteRecordInfo<'ui-pages-authentication-verify-email-v1', '/ui/pages/authentication/verify-email-v1', Record<never, never>, Record<never, never>>,
    'ui-pages-authentication-verify-email-v2': RouteRecordInfo<'ui-pages-authentication-verify-email-v2', '/ui/pages/authentication/verify-email-v2', Record<never, never>, Record<never, never>>,
    'ui-pages-cards-card-actions': RouteRecordInfo<'ui-pages-cards-card-actions', '/ui/pages/cards/card-actions', Record<never, never>, Record<never, never>>,
    'ui-pages-cards-card-advance': RouteRecordInfo<'ui-pages-cards-card-advance', '/ui/pages/cards/card-advance', Record<never, never>, Record<never, never>>,
    'ui-pages-cards-card-basic': RouteRecordInfo<'ui-pages-cards-card-basic', '/ui/pages/cards/card-basic', Record<never, never>, Record<never, never>>,
    'ui-pages-cards-card-statistics': RouteRecordInfo<'ui-pages-cards-card-statistics', '/ui/pages/cards/card-statistics', Record<never, never>, Record<never, never>>,
    'ui-pages-cards-card-widgets': RouteRecordInfo<'ui-pages-cards-card-widgets', '/ui/pages/cards/card-widgets', Record<never, never>, Record<never, never>>,
    'ui-pages-dialog-examples': RouteRecordInfo<'ui-pages-dialog-examples', '/ui/pages/dialog-examples', Record<never, never>, Record<never, never>>,
    'ui-pages-faq': RouteRecordInfo<'ui-pages-faq', '/ui/pages/faq', Record<never, never>, Record<never, never>>,
    'ui-pages-icons': RouteRecordInfo<'ui-pages-icons', '/ui/pages/icons', Record<never, never>, Record<never, never>>,
    'ui-pages-misc-coming-soon': RouteRecordInfo<'ui-pages-misc-coming-soon', '/ui/pages/misc/coming-soon', Record<never, never>, Record<never, never>>,
    'ui-pages-misc-under-maintenance': RouteRecordInfo<'ui-pages-misc-under-maintenance', '/ui/pages/misc/under-maintenance', Record<never, never>, Record<never, never>>,
    'ui-pages-pricing': RouteRecordInfo<'ui-pages-pricing', '/ui/pages/pricing', Record<never, never>, Record<never, never>>,
    'ui-pages-typography': RouteRecordInfo<'ui-pages-typography', '/ui/pages/typography', Record<never, never>, Record<never, never>>,
    'ui-pages-user-profile-tab': RouteRecordInfo<'ui-pages-user-profile-tab', '/ui/pages/user-profile/:tab', { tab: ParamValue<true> }, { tab: ParamValue<false> }>,
    'ui-tables-data-table': RouteRecordInfo<'ui-tables-data-table', '/ui/tables/data-table', Record<never, never>, Record<never, never>>,
    'ui-tables-simple-table': RouteRecordInfo<'ui-tables-simple-table', '/ui/tables/simple-table', Record<never, never>, Record<never, never>>,
    'ui-wizard-examples-checkout': RouteRecordInfo<'ui-wizard-examples-checkout', '/ui/wizard-examples/checkout', Record<never, never>, Record<never, never>>,
    'ui-wizard-examples-create-deal': RouteRecordInfo<'ui-wizard-examples-create-deal', '/ui/wizard-examples/create-deal', Record<never, never>, Record<never, never>>,
    'ui-wizard-examples-property-listing': RouteRecordInfo<'ui-wizard-examples-property-listing', '/ui/wizard-examples/property-listing', Record<never, never>, Record<never, never>>,
  }
}

declare module 'vue-router/auto' {
  import type { RouteNamedMap } from 'vue-router/auto/routes'

  export type RouterTyped = _RouterTyped<RouteNamedMap>

  /**
   * Type safe version of `RouteLocationNormalized` (the type of `to` and `from` in navigation guards).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationNormalized<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationNormalizedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationNormalizedLoaded` (the return type of `useRoute()`).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationNormalizedLoaded<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationResolved` (the returned route of `router.resolve()`).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationResolved<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationResolvedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocation` . Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocation<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationRaw` . Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationRaw<Name extends keyof RouteNamedMap = keyof RouteNamedMap> =
    | RouteLocationAsString<RouteNamedMap>
    | RouteLocationAsRelativeTypedList<RouteNamedMap>[Name]
    | RouteLocationAsPathTypedList<RouteNamedMap>[Name]

  /**
   * Generate a type safe params for a route location. Requires the name of the route to be passed as a generic.
   */
  export type RouteParams<Name extends keyof RouteNamedMap> = RouteNamedMap[Name]['params']
  /**
   * Generate a type safe raw params for a route location. Requires the name of the route to be passed as a generic.
   */
  export type RouteParamsRaw<Name extends keyof RouteNamedMap> = RouteNamedMap[Name]['paramsRaw']

  export function useRouter(): RouterTyped
  export function useRoute<Name extends keyof RouteNamedMap = keyof RouteNamedMap>(name?: Name): RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[Name]

  export const useLink: UseLinkFnTyped<RouteNamedMap>

  export function onBeforeRouteLeave(guard: NavigationGuard<RouteNamedMap>): void
  export function onBeforeRouteUpdate(guard: NavigationGuard<RouteNamedMap>): void

  export const RouterLink: RouterLinkTyped<RouteNamedMap>
  export const RouterLinkProps: RouterLinkPropsTyped<RouteNamedMap>

  // Experimental Data Fetching

  export function defineLoader<
    P extends Promise<any>,
    Name extends keyof RouteNamedMap = keyof RouteNamedMap,
    isLazy extends boolean = false,
  >(
    name: Name,
    loader: (route: RouteLocationNormalizedLoaded<Name>) => P,
    options?: _DefineLoaderOptions<isLazy>,
  ): _DataLoader<Awaited<P>, isLazy>
  export function defineLoader<
    P extends Promise<any>,
    isLazy extends boolean = false,
  >(
    loader: (route: RouteLocationNormalizedLoaded) => P,
    options?: _DefineLoaderOptions<isLazy>,
  ): _DataLoader<Awaited<P>, isLazy>

  export {
    _definePage as definePage,
    _HasDataLoaderMeta as HasDataLoaderMeta,
    _setupDataFetchingGuard as setupDataFetchingGuard,
    _stopDataFetchingScope as stopDataFetchingScope,
  } from 'unplugin-vue-router/runtime'
}

declare module 'vue-router' {
  import type { RouteNamedMap } from 'vue-router/auto/routes'

  export interface TypesConfig {
    beforeRouteUpdate: NavigationGuard<RouteNamedMap>
    beforeRouteLeave: NavigationGuard<RouteNamedMap>

    $route: RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[keyof RouteNamedMap]
    $router: _RouterTyped<RouteNamedMap>

    RouterLink: RouterLinkTyped<RouteNamedMap>
  }
}
